const assert=require('node:assert/strict');
const{readFileSync,readdirSync,statSync}=require('node:fs');
const{join}=require('node:path');
const{test}=require('node:test');
function files(root){return readdirSync(root).flatMap(name=>{const path=join(root,name);return statSync(path).isDirectory()?files(path):/\.(tsx|css)$/.test(path)?[path]:[]})}
test('Claude 1A tokens and intentional dark palette are centralized',()=>{const css=readFileSync('app/globals.css','utf8');for(const token of ['#F7F4EF','#F2EEE2','#221F1A','#6E675C','#3F7D62','#1E4038','#84C9A5','#E2552F'])assert.match(css,new RegExp(token,'i'));assert.match(css,/:root\[data-theme="dark"\]/);for(const file of files('components'))assert.doesNotMatch(readFileSync(file,'utf8'),/#[0-9a-f]{3,8}/i,file)});
test('components use logical RTL spacing and document direction',()=>{for(const file of [...files('app'),...files('components')].filter(file=>file.endsWith('.tsx')))assert.doesNotMatch(readFileSync(file,'utf8'),/\b(?:ml|mr|pl|pr|left|right)-|text-(?:left|right)/,file);const i18n=readFileSync('lib/i18n/index.tsx','utf8');assert.match(i18n,/locale==='he'\?'rtl':'ltr'/);assert.match(i18n,/document\.documentElement\.dir/)});
test('mobile navigation and touch sizes cover 360 and 390 layouts without table overflow',()=>{const css=readFileSync('app/globals.css','utf8');assert.match(css,/\.bottom-nav/);assert.match(css,/--control-height:3rem/);assert.match(css,/button\{min-height:var\(--control-height\)/);assert.match(css,/\.client-mobile-list/);assert.match(css,/@media\(min-width:47.5rem\)/);assert.doesNotMatch(readFileSync('components/tenant/client-directory.tsx','utf8'),/overflow-x/)});
test('controls share sizing tokens, themed checkboxes and remembered desktop navigation collapse',()=>{const css=readFileSync('app/globals.css','utf8'),shell=readFileSync('components/ui/app-shell.tsx','utf8');for(const token of ['--control-height','--control-padding-inline','accent-color:var(--accent)','.sidebar-collapsed'])assert.match(css,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(shell,/leya-sidebar-collapsed/);});
test('ru en and he dictionaries include shared screen, theme and auth keys',()=>{const source=readFileSync('lib/i18n/index.tsx','utf8');for(const locale of ['uiRu','uiEn','uiHe'])assert.match(source,new RegExp(`const ${locale}`));for(const key of ['themeSystem','loginTitle','faqSetupTitle','clientsIntro','settingsIntro'])assert.equal((source.match(new RegExp(`${key}:`,'g'))||[]).length,3,key)});
test('desktop shell swaps logical areas in RTL and collapsed controls stay intact',()=>{const css=readFileSync('app/globals.css','utf8'),shell=readFileSync('components/ui/app-shell.tsx','utf8');assert.match(css,/grid-template-areas:"sidebar main"/);assert.match(css,/\[dir="rtl"\] \.app-shell\{grid-template-areas:"main sidebar"/);assert.match(css,/\.app-shell\.sidebar-collapsed \.collapsed-controls\{display:grid\}/);assert.match(shell,/collapsed\?'›':'‹'/);});
