const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
test('legacy settings response renders from complete runtime defaults',()=>{
 const exports={};vm.runInNewContext(compile('lib/tenant-settings/normalize.ts'),{exports,Date,Number,Object,Array});
 const settings=exports.normalizeTenantSettings({time_zone:'Asia/Jerusalem'}),usage=exports.normalizeUsage({});assert.equal(settings.summary_time,'09:00');assert.equal(settings.summary_weekday,1);
 assert.deepEqual([...settings.campaign_routes],[]);assert.deepEqual([...settings.source_routes],[]);assert.deepEqual([...settings.enabled_agents],['SALE','SUPPORT']);
 assert.equal(Object.keys(settings.weekly_schedule).length,7);assert.doesNotThrow(()=>settings.supported_time_zones.map(String));for(const zone of ['UTC','UTC+1','UTC-12'])assert.ok(settings.supported_time_zones.includes(zone));assert.doesNotThrow(()=>settings.exceptions.map(String));assert.equal(settings.intent_confidence_threshold,.75);assert.equal(settings.route_stickiness_hours,24);assert.equal(settings.reception_max_messages,0);assert.equal(settings.simulator_hourly_limit,30);assert.equal(settings.simulator_daily_limit,100);assert.equal(settings.auto_resume_hours,0);assert.equal(settings.deferred_max_age_hours,12);assert.equal(settings.context_message_count,10);assert.equal(settings.context_retention_hours,48);assert.equal(settings.message_retention_days,30);assert.deepEqual(Object.keys(settings.templates),[]);assert.equal(usage.events.model_calls,0);
});
test('settings sections have independent localized error boundaries',()=>{const page=fs.readFileSync('components/tenant/tenant-settings.tsx','utf8'),boundary=fs.readFileSync('components/tenant/settings-section-boundary.tsx','utf8');assert.ok((page.match(/SettingsSectionBoundary render=/g)||[]).length>=4);assert.match(boundary,/getDerivedStateFromError/);assert.match(boundary,/t\('sectionError'\)/);});
test('server timezone list is supplemented with every UTC offset',()=>{const exports={};vm.runInNewContext(compile('lib/tenant-settings/normalize.ts'),{exports,Date,Number,Object,Array,Set});const zones=exports.normalizeTenantSettings({supported_time_zones:['Asia/Jerusalem','Europe/London']}).supported_time_zones;for(const zone of ['Europe/London','UTC-12','UTC','UTC+1','UTC+14'])assert.ok(zones.includes(zone),zone);});
test('UTC labels are translated before browser Intl formatting',()=>{const exports={};vm.runInNewContext(compile('lib/tenant-settings/time-zone.ts'),{exports});assert.equal(exports.intlTimeZone('UTC+3'),'Etc/GMT-3');assert.equal(exports.intlTimeZone('UTC-5'),'Etc/GMT+5');assert.equal(exports.intlTimeZone('Asia/Jerusalem'),'Asia/Jerusalem');});
test('owner settings use localized plain language and do not expose operator controls',()=>{const page=fs.readFileSync('components/tenant/tenant-settings.tsx','utf8');for(const key of ['whenLeyaAnswers','holidays','contactPhone','capabilities','salesHelp','supportHelp'])assert.match(page,new RegExp(`t\\('${key}'`));assert.match(page,/EmergencyStop showHelp/);for(const text of ['Порог уверенности маршрута','Ключевые слова кампаний','Источники первого сообщения','Пересмотреть маршрут после паузы','Переводить ответы владельца','Повторно уведомить через','Закрыть без ответа через','>Агенты<'])assert.equal(page.includes(text),false,text);assert.match(page,/supported_time_zones\.map/);});
test('owner chooses summary frequency, local time and weekly day',()=>{const page=fs.readFileSync('components/tenant/tenant-settings.tsx','utf8');for(const token of ['summary_frequency','summary_time','summary_weekday',"t('summaryTime')","t('summaryDay')"])assert.match(page,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
