const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
test('legacy settings response renders from complete runtime defaults',()=>{
 const exports={};vm.runInNewContext(compile('lib/tenant-settings/normalize.ts'),{exports,Date,Number,Object,Array});
 const settings=exports.normalizeTenantSettings({time_zone:'Asia/Jerusalem'}),usage=exports.normalizeUsage({});
 assert.deepEqual([...settings.campaign_routes],[]);assert.deepEqual([...settings.source_routes],[]);assert.deepEqual([...settings.enabled_agents],['SALE','SUPPORT']);
 assert.equal(Object.keys(settings.weekly_schedule).length,7);assert.doesNotThrow(()=>settings.supported_time_zones.map(String));for(const zone of ['UTC','UTC+1','UTC-12'])assert.ok(settings.supported_time_zones.includes(zone));assert.doesNotThrow(()=>settings.exceptions.map(String));assert.equal(settings.intent_confidence_threshold,.75);assert.equal(settings.route_stickiness_hours,24);assert.equal(settings.reception_max_messages,0);assert.equal(settings.auto_resume_hours,0);assert.equal(settings.deferred_max_age_hours,12);assert.equal(settings.context_message_count,10);assert.equal(settings.context_retention_hours,48);assert.deepEqual(Object.keys(settings.templates),[]);assert.equal(usage.events.model_calls,0);
});
test('settings sections have independent error boundaries',()=>{const page=fs.readFileSync('components/tenant/tenant-settings.tsx','utf8'),boundary=fs.readFileSync('components/tenant/settings-section-boundary.tsx','utf8');assert.ok((page.match(/SettingsSectionBoundary render=/g)||[]).length>=4);assert.match(boundary,/getDerivedStateFromError/);assert.match(boundary,/Остальные разделы доступны/);});
test('server timezone list is supplemented with every UTC offset',()=>{const exports={};vm.runInNewContext(compile('lib/tenant-settings/normalize.ts'),{exports,Date,Number,Object,Array,Set});const zones=exports.normalizeTenantSettings({supported_time_zones:['Asia/Jerusalem','Europe/London']}).supported_time_zones;for(const zone of ['Europe/London','UTC-12','UTC','UTC+1','UTC+14'])assert.ok(zones.includes(zone),zone);});
test('owner settings use plain language and do not expose operator controls',()=>{const page=fs.readFileSync('components/tenant/tenant-settings.tsx','utf8');for(const text of ['Когда Лея отвечает клиентам','Праздники и отпуска','Телефон для связи','Остановить ответы Леи','Что умеет Лея','Помогать с выбором и покупкой','Отвечать по текущим вопросам и проблемам'])assert.match(page,new RegExp(text));for(const text of ['Порог уверенности маршрута','Ключевые слова кампаний','Источники первого сообщения','Пересмотреть маршрут после паузы','Переводить ответы владельца','Повторно уведомить через','Закрыть без ответа через','>Агенты<'])assert.equal(page.includes(text),false,text);assert.match(page,/supported_time_zones\.map/);});
