'use client';
import type {ButtonHTMLAttributes,ReactNode,SelectHTMLAttributes} from 'react';
import {useI18n} from '@/lib/i18n';

export function Spinner(){return <span className="spinner" aria-hidden="true"/>}
export function LoadingState({label}:{label:string}){return <div className="state-card" role="status"><Spinner/><p>{label}</p></div>}
export function EmptyState({title,action}:{title:string;action?:ReactNode}){return <div className="state-card empty-state"><span className="state-mark">＋</span><p>{title}</p>{action}</div>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){const{t}=useI18n();return <div className="state-card error-state" role="alert"><span className="state-mark">!</span><p>{message}</p>{onRetry&&<button type="button" className="button secondary" onClick={onRetry}>{t('tryAgain')}</button>}</div>}
export function Button({tone='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:'primary'|'secondary'|'danger'|'quiet'}){return <button {...props} className={`button ${tone} ${className}`.trim()}/>}
export function Select({className='',children,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <span className={`select-control ${className}`.trim()}><select {...props}>{children}</select><svg aria-hidden="true" viewBox="0 0 20 20"><path d="m6 8 4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg></span>}
export function Check({checked,onChange,label,description}:{checked:boolean;onChange:(checked:boolean)=>void;label:string;description?:string}){return <label className="check-control"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span className="check-mark" aria-hidden="true">✓</span><span><strong>{label}</strong>{description?<small>{description}</small>:null}</span></label>}
export function SectionHeading({title,help,eyebrow,action}:{title:string;help?:string;eyebrow?:string;action?:ReactNode}){return <div className="section-heading"><div>{eyebrow?<p className="card-kicker">{eyebrow}</p>:null}<h2>{title}</h2>{help?<p>{help}</p>:null}</div>{action}</div>}
export function OwnerContentLanguage({text}:{text:string}){const code=/[\u0590-\u05ff]/.test(text)?'HE':/[\u0400-\u04ff]/.test(text)?'RU':/[A-Za-z]/.test(text)?'EN':'';return code?<span className="content-language" title={code}>{code}</span>:null}
export function Switch({checked,onChange,label}:{checked:boolean;onChange:(checked:boolean)=>void;label:string}){return <label className="switch-row"><span>{label}</span><input className="sr-only" type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span className="switch" aria-hidden="true"><span/></span></label>}
export function ConfirmDialog({open,title,children,danger=false,onCancel,onConfirm}:{open:boolean;title:string;children:ReactNode;danger?:boolean;onCancel:()=>void;onConfirm:()=>void}){const{t}=useI18n();if(!open)return null;return <div className="dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onCancel()}}><section className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><div>{children}</div><div className="dialog-actions"><Button tone="secondary" onClick={onCancel}>{t('cancel')}</Button><Button tone={danger?'danger':'primary'} onClick={onConfirm}>{t('confirmAction')}</Button></div></section></div>}
