'use client';
import {useEffect,useState} from 'react';
import {useFormat,useI18n} from '@/lib/i18n';
import {Button,ConfirmDialog,EmptyState,ErrorState,LoadingState,Switch} from '@/components/ui/primitives';
type Item={id:string;name:string|null;phone:string;status:string;last_seen_at:string|null;inquiry_count:number;current_agent:string|null};
type Card=Item&{language:string|null;first_seen_at:string;notes:string|null;auto_reply_allowed:boolean;auto_reply_opted_out_at:string|null;messages:Array<{id:string;body:string|null;msg_type:string;from_me:boolean;created_at:string}>};
type Confirmation={kind:'hide'|'erase'|'automatic';message:string}|null;
export default function ClientDirectory(){
 const{t}=useI18n(),format=useFormat(),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Card|null>(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[confirmation,setConfirmation]=useState<Confirmation>(null);
 const statuses:Record<string,string>={new:t('newStatus'),active:t('dialogueStatus'),waiting_owner:t('waitingStatus'),closed:t('closedStatus')};
 const load=async()=>{setLoading(true);try{const r=await fetch(`/api/clients?search=${encodeURIComponent(search)}`),j=await r.json();if(!r.ok)throw new Error();setItems(j.clients??j);setError('');}catch{setError(t('loadClientsError'));}finally{setLoading(false)}};
 const open=async(id:string)=>{try{const r=await fetch(`/api/clients/${id}`),j=await r.json();if(!r.ok)throw new Error();setSelected(j.client??j);}catch{setError(t('openCardError'));}};
 // Initial fetch only; later searches are explicitly submitted by the owner.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[]);
 const save=async(body:Record<string,unknown>)=>{if(!selected)return;setBusy(true);try{const r=await fetch(`/api/clients/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error();setSelected(j.client??j);setError('');}catch{setError(t('saveError'));}finally{setBusy(false)}};
 const remove=async(permanent:boolean)=>{if(!selected)return;setBusy(true);try{const r=await fetch(`/api/clients/${selected.id}?permanent=${permanent}`,{method:'DELETE'});if(!r.ok)throw new Error();setSelected(null);await load();}catch{setError(t('deleteError'));}finally{setBusy(false)}};
 const confirmAction=()=>{const action=confirmation?.kind;setConfirmation(null);if(action==='hide')void remove(false);if(action==='erase')void remove(true);if(action==='automatic'&&selected)void save({auto_reply_allowed:!selected.auto_reply_allowed})};
 return <div className="directory">
  {error&&<ErrorState message={error} onRetry={()=>void load()}/>}<form onSubmit={event=>{event.preventDefault();void load()}} className="search-bar"><input aria-label={t('searchClients')} value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('searchClients')}/><Button>{t('find')}</Button></form>
  {loading?<LoadingState label={t('loading')}/>:items.length===0?<EmptyState title={t('noClients')} action={<p>{t('emptyNextStep')}</p>}/>:<><div className="client-mobile-list">{items.map(item=><button type="button" key={item.id} onClick={()=>void open(item.id)} className="client-list-card"><div><strong>{item.name||t('unnamed')}</strong><small>{item.phone}</small></div><span className="status-badge">{statuses[item.status]??item.status}</span><dl><div><dt>{t('lastInquiry')}</dt><dd>{item.last_seen_at?format.dateTime(item.last_seen_at):'—'}</dd></div><div><dt>{t('inquiryCount')}</dt><dd>{format.number(item.inquiry_count)}</dd></div><div><dt>{t('responder')}</dt><dd>{item.current_agent||'—'}</dd></div></dl></button>)}</div><div className="client-table"><table><thead><tr><th>{t('client')}</th><th>{t('status')}</th><th>{t('lastInquiry')}</th><th>{t('inquiryCount')}</th><th>{t('responder')}</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>void open(item.id)}><td><strong>{item.name||t('unnamed')}</strong><small>{item.phone}</small></td><td>{statuses[item.status]??item.status}</td><td>{item.last_seen_at?format.dateTime(item.last_seen_at):'—'}</td><td>{format.number(item.inquiry_count)}</td><td>{item.current_agent||'—'}</td></tr>)}</tbody></table></div></>}
  {selected&&<section className="client-card surface-card"><header><div><p className="card-kicker">{t('client')}</p><h2>{selected.name||t('client')}</h2><p className="technical-value">{selected.phone}</p></div><Button tone="quiet" onClick={()=>setSelected(null)}>{t('close')}</Button></header><div className="client-facts"><label>{t('language')}<select value={selected.language||'ru'} onChange={event=>void save({language:event.target.value})}><option value="ru">{t('russian')}</option><option value="he">{t('hebrew')}</option><option value="en">{t('english')}</option></select></label><p>{t('firstInquiry')}<strong>{format.dateTime(selected.first_seen_at)}</strong></p><p>{t('lastInquiry')}<strong>{selected.last_seen_at?format.dateTime(selected.last_seen_at):'—'}</strong></p><p>{t('status')}<strong>{statuses[selected.status]??selected.status}</strong></p></div><label className="field-label">{t('ownerNote')}<textarea defaultValue={selected.notes||''} onBlur={event=>void save({notes:event.target.value})}/></label><Switch checked={selected.auto_reply_allowed} onChange={()=>setConfirmation({kind:'automatic',message:selected.auto_reply_allowed?t('disableConfirm'):t('enableConfirm')})} label={selected.auto_reply_allowed?t('enableAuto'):t('disableAuto')}/>{selected.auto_reply_opted_out_at&&<p className="muted">{t('disabledAt')}: {format.dateTime(selected.auto_reply_opted_out_at)}</p>}<div><h3>{t('recentMessages')}</h3><div className="message-list">{selected.messages?.length?selected.messages.map(message=><div key={message.id} className={message.from_me?'outgoing':'incoming'}><p>{message.body||`[${message.msg_type}]`}</p><small>{format.dateTime(message.created_at)}</small></div>):<EmptyState title={t('noMessages')}/>}</div></div><div className="danger-actions"><Button disabled={busy} tone="secondary" onClick={()=>setConfirmation({kind:'hide',message:t('hideConfirm')})}>{t('hideCard')}</Button><Button disabled={busy} tone="danger" onClick={()=>setConfirmation({kind:'erase',message:t('eraseConfirm')})}>{t('eraseCard')}</Button></div></section>}
  <ConfirmDialog open={Boolean(confirmation)} title={t('confirmAction')} danger={confirmation?.kind==='erase'} onCancel={()=>setConfirmation(null)} onConfirm={confirmAction}><p>{confirmation?.message}</p></ConfirmDialog>
 </div>;
}
