'use client';
import {type FormEvent,useState} from 'react';
import {Button,EmptyState,ErrorState} from '@/components/ui/primitives';
import {useFormat,useI18n} from '@/lib/i18n';
type Message={role:'owner'|'leya';text:string;at:Date};
export default function ConversationSimulator(){
 const{t}=useI18n(),format=useFormat(),[text,setText]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(event:FormEvent){event.preventDefault();const value=text.trim();if(!value||busy)return;setMessages(rows=>[...rows,{role:'owner',text:value,at:new Date()}]);setText('');setBusy(true);setError('');try{const response=await fetch('/api/simulator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value})}),json=await response.json();if(!response.ok||typeof json.reply!=='string')throw new Error();setMessages(rows=>[...rows,{role:'leya',text:json.reply,at:new Date()}]);}catch{setError(t('simulatorError'));}finally{setBusy(false)}}
 return <section className="surface-card simulator" aria-labelledby="simulator-title"><div className="section-heading"><div><p className="card-kicker">{t('simulatorKicker')}</p><h2 id="simulator-title">{t('simulatorTitle')}</h2><p>{t('simulatorHelp')}</p></div><span className="simulation-badge">{t('simulationOnly')}</span></div><div className="simulator-chat" aria-live="polite">{messages.length===0?<EmptyState title={t('simulatorEmpty')} action={<p>{t('simulatorEmptyHelp')}</p>}/>:messages.map((message,index)=><div key={`${message.at.toISOString()}-${index}`} className={`chat-bubble ${message.role}`}><p dir="auto">{message.text}</p><small>{format.time(message.at)}</small></div>)}{busy?<div className="chat-bubble leya typing"><span/><span/><span/><i>{t('simulatorThinking')}</i></div>:null}</div>{error?<ErrorState message={error}/>:null}<form className="simulator-compose" onSubmit={send}><label className="sr-only" htmlFor="simulation-message">{t('simulatorPlaceholder')}</label><input id="simulation-message" dir="auto" value={text} onChange={event=>setText(event.target.value)} maxLength={2000} placeholder={t('simulatorPlaceholder')}/><Button disabled={busy||!text.trim()}>{t('simulatorSend')}</Button></form></section>;
}
