'use client';
import {type FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {getOnboardingTenant} from '@/lib/onboarding/tenant';
import {Button,EmptyState,ErrorState,LoadingState} from '@/components/ui/primitives';
import {useI18n} from '@/lib/i18n';
type Item={id:string;question:string|null;answer:string};
const presetKeys:Record<string,string[]>= {beauty:['presetBeautyPrice','presetBeautyAddress','presetBeautyCare'],food:['presetFoodOrder','presetFoodDelivery','presetFoodAllergy'],services:['presetServicePrice','presetServiceHours','presetServiceLocation'],other:['presetServicePrice','presetServiceHours']};
export default function KnowledgeEditor({onboarding=false}:{onboarding?:boolean}){const{t}=useI18n(),router=useRouter(),[items,setItems]=useState<Item[]>([]),[tenantId,setTenantId]=useState(''),[query,setQuery]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[editingId,setEditingId]=useState<string|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[canEdit,setCanEdit]=useState(false),[category,setCategory]=useState('other');
 useEffect(()=>{setCategory(typeof sessionStorage==='undefined'?'other':sessionStorage.getItem('onboarding_business_category')||'other');const initial=typeof window==='undefined'||typeof URLSearchParams==='undefined'?null:new URLSearchParams(window.location.search).get('question');if(initial){setQuestion(initial);setOpen(true)};let cancelled=false;void (async()=>{try{const tenant=await getOnboardingTenant(),result=await tenant.supabase.from('knowledge_items').select('id,question,answer').eq('tenant_id',tenant.tenantId).order('created_at').order('id');if(result.error)throw new Error();if(!cancelled){setItems(result.data??[]);setTenantId(tenant.tenantId);try{tenant.requireRole(['owner','admin']);setCanEdit(true)}catch{setCanEdit(false)}}}catch{if(!cancelled)setError(t('faqLoadError'))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[t]);
 const searchValue=query.trim().toLowerCase(),visible=searchValue?items.filter(item=>`${item.question??''} ${item.answer}`.toLowerCase().includes(searchValue)):items;
 function close(){setOpen(false);setEditingId(null);setQuestion('');setAnswer('')}
 function edit(item:Item){setEditingId(item.id);setQuestion(item.question??'');setAnswer(item.answer);setOpen(true)}
 async function save(event:FormEvent){event.preventDefault();if(busy||!question.trim()||!answer.trim())return;setBusy(true);try{const tenant=await getOnboardingTenant();tenant.requireRole(['owner','admin']);if(tenant.tenantId!==tenantId)throw new Error();const values={question:question.trim(),answer:answer.trim()};const request=editingId?tenant.supabase.from('knowledge_items').update(values).eq('tenant_id',tenantId).eq('id',editingId):tenant.supabase.from('knowledge_items').insert({...values,tenant_id:tenantId,type:'faq',language:'he',active:true,source:'manual'});const result=await request.select('id,question,answer').single();if(result.error||!result.data)throw new Error();setItems(rows=>editingId?rows.map(row=>row.id===editingId?result.data:row):[...rows,result.data]);close()}catch{setError(t('faqSaveError'))}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm(t('deleteFaqConfirm')))return;setBusy(true);try{const tenant=await getOnboardingTenant();tenant.requireRole(['owner','admin']);const result=await tenant.supabase.from('knowledge_items').delete().eq('tenant_id',tenantId).eq('id',id);if(result.error)throw new Error();setItems(rows=>rows.filter(row=>row.id!==id))}catch{setError(t('faqDeleteError'))}finally{setBusy(false)}}
 const presets=presetKeys[category]??presetKeys.other!;
 return <div className="knowledge-editor">{onboarding?<><p className="muted">{t('faqIntro')}</p><div className="preset-grid" aria-label={t('faqTemplates')}>{presets.map(key=><button type="button" className="preset-card" key={key} onClick={()=>{const [q,a]=t(key).split('|');setQuestion(q||'');setAnswer(a||'');setOpen(true)}}>{t(key).split('|')[0]}</button>)}</div><Button disabled={!canEdit} onClick={()=>setOpen(true)}>{t('addQuestion')}</Button></>:<div className="knowledge-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('searchKnowledge')}/><Button disabled={!canEdit} onClick={()=>setOpen(true)}>{t('addQuestion')}</Button></div>}{error?<ErrorState message={error}/>:null}{loading?<LoadingState label={t('loading')}/>:visible.length?<ul className="knowledge-list">{visible.map(item=><li key={item.id}><div><strong dir="auto">{item.question||t('withoutQuestion')}</strong><p dir="auto">{item.answer}</p></div><div className="row-actions"><Button tone="quiet" disabled={!canEdit||busy} onClick={()=>edit(item)}>{t('edit')}</Button><Button tone="quiet" disabled={!canEdit||busy} onClick={()=>void remove(item.id)}>{t('delete')}</Button></div></li>)}</ul>:<EmptyState title={query?t('knowledgeNoResults'):t('noQuestionsAtAll')} action={<Button disabled={!canEdit} onClick={()=>setOpen(true)}>{t('addQuestion')}</Button>}/>} {open?<div className="dialog-backdrop" role="presentation"><form className="dialog knowledge-dialog" onSubmit={save}><h2>{editingId?t('editFaq'):t('newFaq')}</h2><label className="field-label" htmlFor="question">{t('question')}<input id="question" dir="auto" required value={question} onChange={event=>setQuestion(event.target.value)}/></label><label className="field-label" htmlFor="answer">{t('answer')}<textarea id="answer" dir="auto" required rows={5} value={answer} onChange={event=>setAnswer(event.target.value)}/></label><div className="dialog-actions"><Button type="button" tone="secondary" onClick={close}>{t('cancel')}</Button><Button disabled={busy||!question.trim()||!answer.trim()}>{busy?t('saving'):t('save')}</Button></div></form></div>:null}{onboarding?<div className="step-actions"><Link href="/onboarding/step-3" className="back-link">{t('back')}</Link><Button disabled={busy} onClick={()=>router.push('/admin')}>{t('finish')}</Button></div>:null}</div>}
