'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useFormat,useI18n} from '@/lib/i18n';
import {ErrorState} from '@/components/ui/primitives';
type Summary={inquiries:number;new_clients:number;closed_by_bot:number;escalated:number;unanswered:number;missing_knowledge:Array<{question:string;count:number}>};
export default function OwnerSummary(){
 const{t}=useI18n(),format=useFormat(),[days,setDays]=useState(7),[data,setData]=useState<Summary|null>(null),[error,setError]=useState('');
 const load=useCallback(async(period=days)=>{try{const to=new Date(),from=new Date(to.getTime()-period*86400000),response=await fetch(`/api/owner-summary?from=${from.toISOString()}&to=${to.toISOString()}`,{cache:'no-store'}),json=await response.json();if(!response.ok)throw new Error();setData(json);setError('');}catch{setError(t('summaryError'))}},[days,t]);
 useEffect(()=>{void load()},[load]);
 return <section className="surface-card summary-card"><div className="section-heading"><h2>{t('summaryTitle')}</h2><select value={days} onChange={event=>setDays(Number(event.target.value))}><option value="1">{t('day')}</option><option value="7">{t('week')}</option><option value="30">{t('month')}</option></select></div>{error?<ErrorState message={error} onRetry={()=>void load()}/>:!data?<div className="metric-grid" aria-label={t('loading')}>{[1,2,3,4].map(item=><div className="metric skeleton" key={item}/>)}</div>:<><div className="metric-grid"><div className="metric primary"><span>{t('inquiries')}</span><strong>{format.number(data.inquiries)}</strong></div><div className="metric"><span>{t('newClients')}</span><strong>{format.number(data.new_clients)}</strong></div><div className="metric success"><span>{t('closedByLeya')}</span><strong>{format.number(data.closed_by_bot)}</strong></div><div className={`metric ${data.unanswered?'attention':''}`}><span>{t('unanswered')}</span><strong>{format.number(data.unanswered)}</strong><small>{t('escalated')}: {format.number(data.escalated)}</small></div></div><div className="knowledge-gap"><div className="gap-icon" aria-hidden="true">?</div><div><h3>{t('missingKnowledge')}</h3>{data.missing_knowledge.length?<ul>{data.missing_knowledge.slice(0,3).map(item=><li key={item.question}><span>{item.question}</span><span className="gap-actions"><b>{format.number(item.count)}</b><Link href={`/admin/knowledge?question=${encodeURIComponent(item.question)}`}>{t('addAnswer')}</Link></span></li>)}</ul>:<p>{t('noGaps')}</p>}</div></div></>}</section>;
}
