'use client';
import {type FormEvent,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {useFormat,useI18n} from '@/lib/i18n';
import type {AccountProfile} from '@/lib/auth/profile';
import {Button} from '@/components/ui/primitives';

export default function ProfilePanel({profile}:{profile:AccountProfile}){
 const{t}=useI18n(),format=useFormat(),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[otherSessionsClosed,setOtherSessionsClosed]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setError('');setSaved(false);if(password!==repeat){setError(t('passwordMismatch'));return}setBusy(true);try{const auth=createClient().auth,verified=await auth.signInWithPassword({email:profile.email,password:current});if(verified.error){setError(t('currentPasswordIncorrect'));return}const result=await auth.updateUser({password});if(result.error){if(result.error.code==='weak_password'){const minimum=(result.error as {weakPassword?:{reasons?:string[]}}).weakPassword?.reasons?.map(reason=>reason.match(/\d+/)?.[0]).find(Boolean);setError(minimum?t('passwordMinimum',{count:minimum}):t('weakPassword'));}else if(result.error.code==='same_password')setError(t('samePassword'));else setError(t('passwordChangeError'));return}setCurrent('');setPassword('');setRepeat('');setSaved(true);}catch{setError(t('passwordChangeError'))}finally{setBusy(false)}}
 async function closeOtherSessions(){setBusy(true);setError('');const{error}=await createClient().auth.signOut({scope:'others'});setBusy(false);if(error)setError(t('otherSessionsError'));else setOtherSessionsClosed(true)}
 return <div className="content-stack"><header className="page-heading"><div><p className="eyebrow">Leya</p><h1>{t('profileTitle')}</h1><p>{t('profileHelp')}</p></div></header><section className="surface-card profile-details"><h2>{t('accountDetails')}</h2><dl><div><dt>{t('email')}</dt><dd>{profile.email}</dd></div><div><dt>{t('businessLabel')}</dt><dd>{profile.businessName}</dd></div><div><dt>{t('businessRole')}</dt><dd>{t(`role_${profile.role}`)}</dd></div><div><dt>{t('registrationDate')}</dt><dd>{profile.createdAt?format.date(profile.createdAt):t('notAssigned')}</dd></div></dl></section><section className="surface-card"><h2>{t('changePassword')}</h2><p className="muted">{t('changePasswordHelp')}</p><form className="profile-password-form" onSubmit={submit}><label className="field-label" htmlFor="current-password">{t('currentPassword')}<input id="current-password" type="password" autoComplete="current-password" required value={current} onChange={event=>setCurrent(event.target.value)}/></label><label className="field-label" htmlFor="new-password">{t('newPassword')}<input id="new-password" type="password" autoComplete="new-password" required value={password} onChange={event=>setPassword(event.target.value)}/></label><label className="field-label" htmlFor="confirm-password">{t('repeatPassword')}<input id="confirm-password" type="password" autoComplete="new-password" required value={repeat} onChange={event=>setRepeat(event.target.value)}/></label>{error?<p role="alert" className="error-copy">{error}</p>:null}{saved?<div className="password-success" role="status"><p>{t('passwordChanged')}</p><Button type="button" tone="secondary" disabled={busy||otherSessionsClosed} onClick={()=>void closeOtherSessions()}>{otherSessionsClosed?t('otherSessionsClosed'):t('closeOtherSessions')}</Button></div>:null}<Button disabled={busy}>{busy?t('saving'):t('savePassword')}</Button></form></section></div>;
}
