"use client";
import {useEffect,useState,type FormEvent} from 'react';
import SettingsSectionBoundary from './settings-section-boundary';
import {normalizeTenantSettings,normalizeUsage} from '@/lib/tenant-settings/normalize';
import {intlTimeZone} from '@/lib/tenant-settings/time-zone';
const DAYS=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];
type Day={mode:'working_day'|'day_off'|'working_hours';start?:string;end?:string};type Schedule=Record<string,Day>;
type X={id:string;start_date:string;end_date:string;kind:'day_off'|'special_hours';work_start:string|null;work_end:string|null;name:string;recurs_annually:boolean};
type Route={keyword?:string;source?:string;agent:string};type S={messages_per_month:number;voice_minutes_per_month:number;warning_percent:number;plan:string|null;time_zone:string;supported_time_zones:string[];weekly_schedule:Schedule;auto_replies_paused:boolean;translate_owner_answer:boolean;escalation_remind_minutes:number;escalation_close_minutes:number;auto_resume_hours:number;deferred_max_age_hours:number;context_message_count:number;context_retention_hours:number;enabled_agents:string[];intent_confidence_threshold:number;route_stickiness_hours:number;reception_max_messages:number;campaign_routes:Route[];source_routes:Route[];owner_phone:string;paired:boolean;exceptions:X[];summary_frequency:'off'|'daily'|'weekly';summary_time:string;summary_weekday:number};
type U={messages_used:number;voice_minutes_used:number;period_end:string;time_zone:string;events:{model_calls:number;stt_calls?:number}};
const blank=():Omit<X,'id'>=>({start_date:'',end_date:'',kind:'day_off',work_start:null,work_end:null,name:'',recurs_annually:false});
const iso=(d:Date)=>d.toISOString().slice(0,10);
function ExceptionCalendar({items,selectedStart,selectedEnd,onRange,onRemove}:{items:X[];selectedStart:string;selectedEnd:string;onRange:(a:string,b:string)=>void;onRemove:(id:string)=>void}){
 const[month,setMonth]=useState(()=>{const d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1));}),[drag,setDrag]=useState<string|null>(null);
 const first=(month.getUTCDay()+6)%7,total=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,0)).getUTCDate();
 const cells=Array.from({length:first+total},(_,i)=>i<first?null:new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth(),i-first+1)));
 const match=(date:string)=>items.find(x=>{if(!x.recurs_annually)return date>=x.start_date&&date<=x.end_date;const value=date.slice(5),a=x.start_date.slice(5),b=x.end_date.slice(5);return a<=b?value>=a&&value<=b:value>=a||value<=b;});
 const finish=(date:string)=>{if(!drag)return;const found=drag===date?match(date):undefined;if(found)onRemove(found.id);else onRange(drag<date?drag:date,drag<date?date:drag);setDrag(null);};
 return <div className="select-none rounded-xl border p-4"><div className="mb-3 flex items-center justify-between"><button type="button" onClick={()=>setMonth(new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()-1,1)))}>←</button><strong>{month.toLocaleDateString('ru',{month:'long',year:'numeric',timeZone:'UTC'})}</strong><button type="button" onClick={()=>setMonth(new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,1)))}>→</button></div><div className="grid grid-cols-7 gap-1 text-center text-sm">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=><b key={x}>{x}</b>)}{cells.map((date,i)=>{if(!date)return <span key={`blank-${i}`}/>;const value=iso(date),marked=match(value),selected=Boolean(selectedStart&&value>=selectedStart&&value<=(selectedEnd||selectedStart));return <button type="button" key={value} title={marked?.name} onPointerDown={e=>{e.preventDefault();setDrag(value);}} onPointerEnter={e=>{if(drag&&e.buttons)onRange(drag<value?drag:value,drag<value?value:drag);}} onPointerUp={()=>finish(value)} className={`rounded p-2 ${selected?'bg-blue-600 font-bold text-white':marked?.kind==='day_off'?'bg-red-200 text-red-900':marked?'bg-amber-200 text-amber-900':'hover:bg-blue-50'} ${marked?.recurs_annually?'ring-2 ring-purple-500':''}`}>{date.getUTCDate()}</button>;})}</div><p className="mt-3 text-xs text-gray-500">Красный — выходной, жёлтый — особые часы, фиолетовая рамка — ежегодно. Клик по отмеченному дню снимает исключение; протяните по дням для диапазона.</p></div>;
}
export default function TenantSettings(){
 const[s,setS]=useState<S|null>(null),[u,setU]=useState<U|null>(null),[draft,setDraft]=useState(blank()),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pairing,setPairing]=useState('');
 async function load(){const r=await fetch('/api/tenant-settings',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setS(normalizeTenantSettings(d.settings) as S);setU(normalizeUsage(d.usage) as U);}
 useEffect(()=>{void load().catch(()=>setError('Не удалось загрузить настройки.'));},[]);
 const update=<K extends keyof S>(k:K,v:S[K])=>setS(x=>x?{...x,[k]:v}:x);
 const day=(key:string,p:Partial<Day>)=>setS(x=>x?{...x,weekly_schedule:{...x.weekly_schedule,[key]:{...x.weekly_schedule[key],...p}}}:x);
 async function save(e:FormEvent){e.preventDefault();if(!s)return;setBusy(true);setError('');try{const body={time_zone:s.time_zone,weekly_schedule:s.weekly_schedule,auto_replies_paused:s.auto_replies_paused,enabled_agents:s.enabled_agents,summary_frequency:s.summary_frequency,summary_time:s.summary_time,summary_weekday:s.summary_weekday};const r=await fetch('/api/tenant-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);await load();setNotice('Настройки сохранены.');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить.');}finally{setBusy(false);}}
 async function pair(){if(!s)return;setBusy(true);try{const r=await fetch('/api/owner-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:s.owner_phone,timeZone:s.time_zone})}),d=await r.json();if(!r.ok)throw new Error(d.error);setPairing(d.pairingCommand);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить номер.');}finally{setBusy(false);}}
 async function saveX(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/schedule-exceptions'+(editing?`?id=${editing}`:''),{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json();if(!r.ok)throw new Error(d.error);setDraft(blank());setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить исключение.');}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);try{const r=await fetch(`/api/schedule-exceptions?id=${id}`,{method:'DELETE'});if(!r.ok)throw new Error();await load();}catch{setError('Не удалось удалить исключение.');}finally{setBusy(false);}}
 if(!s)return <p>{error||'Загрузка настроек…'}</p>;
 return <div className="space-y-6">{error&&<p role="alert" className="text-red-600">{error}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}
  <SettingsSectionBoundary render={()=>u?<section className="rounded-2xl bg-white p-8 shadow-sm"><h2 className="mb-4 text-xl font-bold">Тариф и расход</h2><p className="mb-3 text-sm text-gray-500">Здесь видно, сколько возможностей тарифа уже использовано в этом месяце.</p><p>Тариф: {s.plan||'Не назначен'}</p><p>Сообщения: {u.messages_used} / {s.messages_per_month}</p><p>Голосовые: {Number(u.voice_minutes_used).toFixed(1)} / {s.voice_minutes_per_month} мин.</p><p>Предупреждение появится после использования {s.warning_percent}%</p><p>Ответы с помощью ИИ: {u.events.model_calls}</p><p>Распознанные голосовые: {u.events.stt_calls??0}</p><p className="mt-3 text-gray-500">Обнуление: {new Date(u.period_end).toLocaleDateString('ru',{timeZone:intlTimeZone(u.time_zone)})}</p></section>:null}/>
  <SettingsSectionBoundary render={()=><section className="space-y-4 rounded-2xl bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Праздники и отпуска</h2><p className="text-sm text-gray-500">В отмеченные дни Лея не отвечает или работает по особому расписанию.</p><ExceptionCalendar items={s.exceptions} selectedStart={draft.start_date} selectedEnd={draft.end_date} onRange={(start_date,end_date)=>setDraft(x=>({...x,start_date,end_date}))} onRemove={id=>void remove(id)}/>{s.exceptions.length===0&&<p>Праздники и отпуска пока не добавлены.</p>}{s.exceptions.map(x=><div key={x.id} className="rounded border p-3"><strong>{x.name}</strong><p>{x.start_date} — {x.end_date}{x.recurs_annually?' · ежегодно':''}</p><p>{x.kind==='day_off'?'Выходной':`Рабочие часы ${x.work_start?.slice(0,5)}—${x.work_end?.slice(0,5)}`}</p><button className="mr-4 text-blue-600" onClick={()=>{setEditing(x.id);setDraft({...x});}}>Изменить</button><button className="text-red-600" onClick={()=>void remove(x.id)}>Удалить</button></div>)}<form onSubmit={saveX} className="space-y-3"><h3 className="font-bold">{editing?'Изменить':'Добавить'} исключение</h3><p>{draft.start_date?`Выбрано: ${draft.start_date} — ${draft.end_date}`:'Выберите день или диапазон в календаре'}</p><input required placeholder="Название" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="block w-full rounded border p-2"/><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as X['kind'],work_start:null,work_end:null})} className="rounded border p-2"><option value="day_off">Выходной</option><option value="special_hours">Особые часы</option></select>{draft.kind==='special_hours'&&<div className="flex gap-3"><input aria-label="Особые часы с" required type="time" value={draft.work_start||''} onChange={e=>setDraft({...draft,work_start:e.target.value})} className="rounded border p-2"/><input aria-label="Особые часы до" required type="time" value={draft.work_end||''} onChange={e=>setDraft({...draft,work_end:e.target.value})} className="rounded border p-2"/></div>}<label className="block"><input type="checkbox" checked={draft.recurs_annually} onChange={e=>setDraft({...draft,recurs_annually:e.target.checked})}/> Повторять ежегодно</label><button disabled={busy||!draft.start_date} className="text-blue-600">Сохранить</button>{editing&&<button type="button" className="ml-4" onClick={()=>{setEditing(null);setDraft(blank());}}>Отмена</button>}</form></section>}/>
  <SettingsSectionBoundary render={()=><form onSubmit={save} className="space-y-5 rounded-2xl bg-white p-8 shadow-sm"><fieldset disabled={busy} className="space-y-5"><h2 className="text-xl font-bold">Когда Лея отвечает клиентам</h2><p className="text-sm text-gray-500">Выберите местное время бизнеса и часы, когда Лея может отвечать клиентам.</p><label className="block">Часовой пояс<select value={s.time_zone} onChange={e=>update('time_zone',e.target.value)} className="mt-1 block w-full rounded-lg border p-3">{s.supported_time_zones.map(z=><option key={z}>{z}</option>)}</select></label>
   {DAYS.map((label,i)=>{const v=s.weekly_schedule[String(i)];return <div key={label} className="rounded-lg border p-3"><div className="flex flex-wrap items-center gap-3"><span className="w-32 font-medium">{label}</span><select value={v.mode} onChange={e=>day(String(i),{mode:e.target.value as Day['mode'],...(e.target.value==='working_hours'?{start:v.start||'09:00',end:v.end||'18:00'}:{})})} className="rounded border p-2"><option value="working_day">Лея отвечает весь день</option><option value="day_off">Лея не отвечает</option><option value="working_hours">Указать часы</option></select>{v.mode==='working_hours'&&<><input aria-label={`${label} с`} type="time" value={v.start||''} onChange={e=>day(String(i),{start:e.target.value})} className="rounded border p-2"/><span>—</span><input aria-label={`${label} до`} type="time" value={v.end||''} onChange={e=>day(String(i),{end:e.target.value})} className="rounded border p-2"/></>}</div></div>;})}
   <div><h3 className="font-bold">Сводка владельцу</h3><p className="mb-2 text-sm text-gray-500">Выберите, как часто и в какое время получать короткий итог по обращениям клиентов.</p><div className="flex flex-wrap gap-3"><select value={s.summary_frequency} onChange={e=>update('summary_frequency',e.target.value as S['summary_frequency'])} className="rounded border p-2"><option value="off">Не отправлять</option><option value="daily">Каждый день</option><option value="weekly">Раз в неделю</option></select><input aria-label="Время сводки" type="time" value={s.summary_time} onChange={e=>update('summary_time',e.target.value)} className="rounded border p-2"/>{s.summary_frequency==='weekly'&&<select aria-label="День сводки" value={s.summary_weekday} onChange={e=>update('summary_weekday',Number(e.target.value))} className="rounded border p-2">{DAYS.map((day,index)=><option key={day} value={index}>{day}</option>)}</select>}</div></div><div><h3 className="font-bold">Ответы клиентам</h3><p className="mb-2 text-sm text-gray-500">Включите паузу, если хотите временно отвечать клиентам самостоятельно.</p><label className="block"><input type="checkbox" checked={s.auto_replies_paused} onChange={e=>update('auto_replies_paused',e.target.checked)}/> Остановить ответы Леи</label></div><div><h3 className="font-bold">Что умеет Лея</h3><p className="mb-2 text-sm text-gray-500">Выберите, с какими обращениями клиентов Лея будет помогать.</p><label className="mr-6"><input type="checkbox" checked={s.enabled_agents.includes('SALE')} onChange={e=>update('enabled_agents',e.target.checked?[...s.enabled_agents,'SALE']:s.enabled_agents.filter(x=>x!=='SALE'))}/> Помогать с выбором и покупкой</label><label><input type="checkbox" checked={s.enabled_agents.includes('SUPPORT')} onChange={e=>update('enabled_agents',e.target.checked?[...s.enabled_agents,'SUPPORT']:s.enabled_agents.filter(x=>x!=='SUPPORT'))}/> Отвечать по текущим вопросам и проблемам</label></div><button className="rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white">Сохранить настройки</button></fieldset></form>}/>
  <SettingsSectionBoundary render={()=><section className="space-y-4 rounded-2xl bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Телефон для связи</h2><p className="text-sm text-gray-500">На этот номер Лея отправляет вопросы клиентов, когда нужен ваш ответ.</p><input type="tel" value={s.owner_phone} onChange={e=>update('owner_phone',e.target.value)} className="block w-full rounded border p-3"/><p>{s.paired?'Номер подтверждён':'Номер не подтверждён'}</p><button disabled={busy} onClick={()=>void pair()} className="text-blue-600">Сохранить и подтвердить</button>{pairing&&<p>Отправьте с личного номера: <strong>{pairing}</strong></p>}</section>}/>
 </div>;
}
