"use client";
import { useEffect,useState,type FormEvent } from 'react';
type Settings={messages_per_month:number;voice_minutes_per_month:number;warning_percent:number;time_zone:string;quiet_hours_start:string;quiet_hours_end:string;auto_replies_paused:boolean;translate_owner_answer:boolean;escalation_remind_minutes:number;escalation_close_minutes:number;enabled_agents:string[];default_agent:string;owner_phone:string;paired:boolean};
type Usage={messages_used:number;messages_limit:number;voice_minutes_used:number;voice_minutes_limit:number;period_end:string;time_zone:string;events:{model_calls:number;stt_calls?:number}};
const numbers=[['messages_per_month','Сообщений в месяц'],['voice_minutes_per_month','Голосовых минут в месяц'],['warning_percent','Предупреждение при расходе, %'],['escalation_remind_minutes','Повторно уведомить владельца через, мин.'],['escalation_close_minutes','Закрыть без ответа через, мин.']] as const;
export default function TenantSettings(){
 const [settings,setSettings]=useState<Settings|null>(null),[usage,setUsage]=useState<Usage|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pairing,setPairing]=useState('');
 async function load(){const r=await fetch('/api/tenant-settings',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setSettings(data.settings);setUsage(data.usage);}
 useEffect(()=>{let live=true;fetch('/api/tenant-settings',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(live){setSettings(d.settings);setUsage(d.usage);}}).catch(()=>{if(live)setError('Не удалось загрузить настройки. Обновите страницу.');});return()=>{live=false;};},[]);
 function update<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(s=>s?{...s,[key]:value}:s);}
 async function save(e:FormEvent){e.preventDefault();if(!settings)return;setBusy(true);setError('');setNotice('');try{
  const {owner_phone,paired,...body}=settings;void owner_phone;void paired;
  const r=await fetch('/api/tenant-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setNotice('Настройки сохранены.');
 }catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить настройки.');}finally{setBusy(false);}}
 async function pair(){if(!settings)return;setBusy(true);setError('');try{const r=await fetch('/api/owner-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:settings.owner_phone,timeZone:settings.time_zone,quietStart:settings.quiet_hours_start,quietEnd:settings.quiet_hours_end})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPairing(d.pairingCommand);setNotice('Номер сохранён. Подтвердите его сообщением с личного WhatsApp.');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить номер.');}finally{setBusy(false);}}
 return <>{error&&<p role="alert" className="text-red-600">{error}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}{!settings?<p>Загрузка настроек…</p>:<>
 {usage&&<section className="rounded-2xl bg-white p-8 shadow-sm"><h2 className="mb-4 text-xl font-bold">Расход в этом месяце</h2><p>Сообщения: {usage.messages_used} / {usage.messages_limit}</p><p>Голосовые: {Number(usage.voice_minutes_used).toFixed(1)} / {usage.voice_minutes_limit} мин.</p><p>Вызовы модели: {usage.events.model_calls}</p><p>Распознавания: {usage.events.stt_calls??0}</p><p className="mt-3 text-gray-500">Обнуление: {new Date(usage.period_end).toLocaleString('ru',{timeZone:usage.time_zone})} ({usage.time_zone})</p><button type="button" disabled={busy} onClick={()=>void load().catch(()=>setError('Не удалось обновить расход.'))} className="mt-3 text-blue-600">Обновить расход</button></section>}
 <form onSubmit={save} className="space-y-5 rounded-2xl bg-white p-8 shadow-sm"><fieldset disabled={busy} className="space-y-5">
 {numbers.map(([key,label])=><label key={key} className="block">{label}<input type="number" required min={key==='warning_percent'||key.includes('escalation')?1:0} max={key==='warning_percent'?100:2147483647} value={settings[key]} onChange={e=>update(key,Number(e.target.value))} className="mt-1 block w-full rounded-lg border p-3"/></label>)}
 <p className="text-sm text-gray-500">Время тихих часов не входит в ожидание ответа владельца.</p>
 <label className="block">Часовой пояс владельца<input required value={settings.time_zone} placeholder="Asia/Jerusalem" onChange={e=>update('time_zone',e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label>
 <div className="flex gap-4">{(['quiet_hours_start','quiet_hours_end'] as const).map((key,i)=><label key={key}>{i?'Тихие часы до':'Тихие часы с'}<input type="time" value={settings[key]} onChange={e=>update(key,e.target.value)} className="mt-1 block rounded-lg border p-3"/></label>)}</div>
 <button type="button" onClick={()=>{update('quiet_hours_start','');update('quiet_hours_end','');}} className="text-blue-600">Отключить тихие часы</button>
 <label className="block"><input type="checkbox" checked={settings.auto_replies_paused} onChange={e=>update('auto_replies_paused',e.target.checked)}/> Пауза автоответов</label>
 <label className="block"><input type="checkbox" checked={settings.translate_owner_answer} onChange={e=>update('translate_owner_answer',e.target.checked)}/> Переводить ответы владельца на язык клиента</label>
 <div><h2 className="mb-2 font-bold">Агенты</h2>{['SALE','SUPPORT'].map(name=><label key={name} className="mr-6"><input type="checkbox" checked={settings.enabled_agents.includes(name)} onChange={e=>update('enabled_agents',e.target.checked?[...settings.enabled_agents,name]:settings.enabled_agents.filter(v=>v!==name))}/> {name==='SALE'?'SALE — услуги и продажи':'SUPPORT — поддержка'}</label>)}</div>
 <label className="block">Агент по умолчанию<select value={settings.default_agent} onChange={e=>update('default_agent',e.target.value)} className="ml-3 rounded-lg border p-3">{['SALE','SUPPORT'].map(name=><option key={name}>{name}</option>)}</select></label>
 <button type="submit" className="rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white">{busy?'Сохраняем…':'Сохранить настройки'}</button>
 </fieldset></form>
 <section className="space-y-4 rounded-2xl bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Личный номер владельца</h2><p>Отдельный номер для вопросов и уведомлений. Он должен отличаться от номера бота.</p><label className="block">Номер с кодом страны<input type="tel" value={settings.owner_phone} onChange={e=>update('owner_phone',e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label><p>{settings.paired?'Номер подтверждён':'Номер ещё не подтверждён'}</p><button type="button" disabled={busy} onClick={()=>void pair()} className="text-blue-600">Сохранить и подтвердить номер</button>{pairing&&<p className="break-all">Отправьте с личного номера в WhatsApp бота: <strong>{pairing}</strong></p>}</section>
 </>}</>;
}
